- name: Install packages
  become: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - ufw
      - git
      - vim
      - tree
      - zip
      - unzip
      - tar
      - gzip
      - bzip2
      - inotify-tools
      - nginx
      - python-pil 
      - python-sphinx 
      - python-sphinxcontrib.phpdomain 
      - rst2pdf 
      - texlive-fonts-recommended 
      - texlive-latex-extra 
      - texlive-latex-recommended

- name: Set firewall default policy
  ufw: state=enabled policy=deny
  become: true

- name: Allow ssh
  ufw: rule=allow port=22 proto=tcp
  become: true

- name: Allow ssh
  ufw: rule=allow port=80 proto=tcp
  become: true

- name: Allow ssh
  ufw: rule=allow port=22020 proto=tcp
  become: true

- name: Configure the default nginx server block
  sudo: true
  template: src=nginx.default.conf dest=/etc/nginx/sites-available/default
    owner={{ webuser }}
    group={{ webgroup }}
    mode=0755
  notify:
    - restart nginx

- name: Configure the nginx server block for the admin manual
  sudo: true
  template: src=nginx.admin-manual.conf dest=/etc/nginx/sites-available/admin-manual
    owner={{ webuser }}
    group={{ webgroup }}
    mode=0755
  notify:
    - restart nginx

- name: link nginx partner-portal vhost in sites-enabled
  action: file src=/etc/nginx/sites-available/admin-manual dest=/etc/nginx/sites-enabled/admin-manual state=link
  notify:
    - restart nginx

- name: Configure the nginx server block for the developer manual
  sudo: true
  template: src=nginx.developer-manual.conf dest=/etc/nginx/sites-available/developer-manual
    owner={{ webuser }}
    group={{ webgroup }}
    mode=0755
  notify:
    - restart nginx

- name: link nginx partner-portal vhost in sites-enabled
  action: file src=/etc/nginx/sites-available/developer-manual dest=/etc/nginx/sites-enabled/developer-manual state=link
  notify:
    - restart nginx

- name: Configure the nginx server block for the user manual
  sudo: true
  template: src=nginx.user-manual.conf dest=/etc/nginx/sites-available/user-manual
    owner={{ webuser }}
    group={{ webgroup }}
    mode=0755
  notify:
    - restart nginx

- name: link nginx partner-portal vhost in sites-enabled
  action: file src=/etc/nginx/sites-available/user-manual dest=/etc/nginx/sites-enabled/user-manual state=link
  notify:
    - restart nginx

